import json
import sys

breed_powers = {
    'chikipi': 1500,
    'teafant': 1490,
    'mau': 1480,
    'lamball': 1470,
    'cattiva': 1460,
    'cremis': 1455,
    'vixy': 1450,
    'mau cryst': 1440,
    'lifmunk': 1430,
    'hangyu cryst': 1422,
    'hangyu': 1420,
    'sparkit': 1410,
    'flambelle': 1405,
    'foxparks': 1400,
    'hoocrates': 1390,
    'depresso': 1380,
    'jolthog': 1370,
    'jolthog cryst': 1360,
    'pengullet': 1350,
    'tocotoco': 1340,
    'fuack': 1330,
    'bristla': 1320,
    'ribunny': 1310,
    'swee': 1300,
    'killamari': 1290,
    'flopie': 1280,
    'kelpsea ignis': 1270,
    'kelpsea': 1260,
    'tanzee': 1250,
    'gumoss': 1240,
    'gumoss (special)': 1240,
    'daedream': 1230,
    'fuddler': 1220,
    'dazzi': 1210,
    'woolipop': 1190,
    'nox': 1180,
    'wixen': 1160,
    'rooby': 1155,
    'maraith': 1150,
    'leezpunk ignis': 1140,
    'rushoar': 1130,
    'leezpunk': 1120,
    'lunaris': 1110,
    'gobfin ignis': 1100,
    'gobfin': 1090,
    'cawgnito': 1080,
    'beegarde': 1070,
    'direhowl': 1060,
    'vaelet': 1050,
    'gorirat': 1040,
    'galeclaw': 1030,
    'robinquill': 1020,
    'felbat': 1010,
    'robinquill terra': 1000,
    'verdash': 990,
    'fenglope': 980,
    'loupmoon': 950,
    'lovander': 940,
    'caprity': 930,
    'eikthyrdeer': 920,
    'mozzarina': 910,
    'eikthyrdeer terra': 900,
    'dumud': 895,
    'melpaca': 890,
    'reindrix': 880,
    'celaray': 870,
    'broncherry': 860,
    'digtoise': 850,
    'broncherry aqua': 840,
    'kitsun': 830,
    'dinossom': 820,
    'dinossom lux': 810,
    'chillet': 800,
    'arsox': 790,
    'petallia': 780,
    'foxcicle': 760,
    'tombat': 750,
    'rayhound': 740,
    'blazehowl': 710,
    'katress': 700,
    'univolt': 680,
    'blazehowl noct': 670,
    'vanwyrm': 660,
    'bushi': 640,
    'vanwyrm cryst': 620,
    'incineram': 590,
    'incineram noct': 580,
    'anubis': 570,
    'surfent': 560,
    'surfent terra': 550,
    'elphidran': 540,
    'elphidran aqua': 530,
    'penking': 520,
    'grintale': 510,
    'azurobe': 500,
    'cinnamoth': 490,
    'wumpo botan': 480,
    'kingpaca': 470,
    'wumpo': 460,
    'sibelyx': 450,
    'ice kingpaca': 440,
    'mossanda': 430,
    'nitewing': 420,
    'sweepa': 410,
    'mossanda lux': 390,
    'ragnahawk': 380,
    'faleris': 370,
    'pyrin': 360,
    'quivern': 350,
    'warsect': 340,
    'elizabee': 330,
    'reptyro': 320,
    'jormuntide ignis': 315,
    'jormuntide': 310,
    'mammorest': 300,
    'mammorest cryst': 290,
    'relaxaurus': 280,
    'relaxaurus lux': 270,
    'menasting': 260,
    'lyleen': 250,
    'pyrin noct': 240,
    'reptyro cryst': 230,
    'beakon': 220,
    'lyleen noct': 210,
    'grizzbolt': 200,
    'helzephyr': 190,
    'astegon': 150,
    'orserk': 140,
    'cryolinx': 130,
    'frostallion': 120,
    'frostallion noct': 100,
    'jetragon': 90,
    'paladius': 80,
    'necromus': 70,
    'shadowbeak': 60,
    'suzaku': 50,
    'suzaku aqua': 30,
    'blazamut': 10
}

tiebreak_order = [
    'anubis',
    'incineram',
    'incineram noct',
    'mau',
    'mau cryst',
    'rushoar',
    'lifmunk',
    'tocotoco',
    'eikthyrdeer',
    'eikthyrdeer terra',
    'digtoise',
    'galeclaw',
    'grizzbolt',
    'teafant',
    'direhowl',
    'gorirat',
    'jolthog',
    'jolthog cryst',
    'univolt',
    'foxparks',
    'bristla',
    'lunaris',
    'pengullet',
    'dazzi',
    'gobfin',
    'gobfin ignis',
    'lamball',
    'jormuntide',
    'jormuntide ignis',
    'loupmoon',
    'hangyu',
    'hangyu cryst',
    'suzaku',
    'suzaku aqua',
    'pyrin',
    'pyrin noct',
    'elphidran',
    'elphidran aqua',
    'woolipop',
    'cryolinx',
    'melpaca',
    'surfent',
    'surfent terra',
    'cawgnito',
    'azurobe',
    'cattiva',
    'depresso',
    'fenglope',
    'reptyro',
    'reptyro cryst',
    'maraith',
    'robinquill',
    'robinquill terra',
    'relaxaurus',
    'relaxaurus lux',
    'kitsun',
    'leezpunk',
    'leezpunk ignis',
    'fuack',
    'vanwyrm',
    'vanwyrm cryst',
    'chikipi',
    'dinossom',
    'dinossom lux',
    'sparkit',
    'frostallion',
    'frostallion noct',
    'mammorest',
    'mammorest cryst',
    'felbat',
    'broncherry',
    'broncherry aqua',
    'faleris',
    'blazamut',
    'caprity',
    'reindrix',
    'shadowbeak',
    'sibelyx',
    'vixy',
    'wixen',
    'lovander',
    'hoocrates',
    'kelpsea',
    'kelpsea ignis',
    'killamari',
    'mozzarina',
    'wumpo',
    'wumpo botan',
    'vaelet',
    'nitewing',
    'flopie',
    'lyleen',
    'lyleen noct',
    'elizabee',
    'beegarde',
    'tombat',
    'mossanda',
    'mossanda lux',
    'arsox',
    'rayhound',
    'fuddler',
    'astegon',
    'verdash',
    'foxcicle',
    'jetragon',
    'daedream',
    'tanzee',
    'blazehowl',
    'blazehowl noct',
    'kingpaca',
    'ice kingpaca',
    'gumoss',
    'gumoss (special)',
    'swee',
    'sweepa',
    'katress',
    'ribunny',
    'beakon',
    'warsect',
    'paladius',
    'nox',
    'penking',
    'chillet',
    'quivern',
    'helzephyr',
    'ragnahawk',
    'bushi',
    'celaray',
    'necromus',
    'petallia',
    'grintale',
    'cinnamoth',
    'menasting',
    'orserk',
    'cremis',
    'dumud',
    'flambelle',
    'rooby'
]

specials = set([
    'relaxaurus lux',
    'incineram noct',
    'mau cryst',
    'vanwyrm cryst',
    'eikthyrdeer terra',
    'elphidran aqua',
    'pyrin noct',
    'mammorest cryst',
    'mossanda lux',
    'dinossom lux',
    'jolthog cryst',
    'frostallion noct',
    'ice kingpaca',
    'lyleen noct',
    'leezpunk ignis',
    'blazehowl noct',
    'robinquill terra',
    'broncherry aqua',
    'surfent terra',
    'gobfin ignis',
    'suzaku aqua',
    'reptyro cryst',
    'hangyu cryst',
    'lyleen',
    'faleris',
    'grizzbolt',
    'orserk',
    'shadowbeak',
])

data = [
    {
        "index": i,
        "name": name,
        "power": power,
        "tiebreak_order": tiebreak_order.index(name),
        "special": name in specials
    } for i, (name, power) in enumerate(breed_powers.items())
]

json.dump(data, sys.stdout)
